spring:
  datasource:
    url: jdbc:mysql://localhost:3307/job_database
    username: admin
    password: admin-gespyme-2024-99Pabcde
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8084

customer:
  endpoint: http://localhost:8081

employee:
  endpoint: http://localhost:8085

calendar:
  adminEmail: admi.gespyme@gmail.com
  timezone: Europe/Madrid

aws:
  roleArn: arn:aws:iam::442042545308:role/gespyme-s3
  region: eu-north-1
  roleSessionName: invoiceServiceSession

  s3:
    bucketname: gespyme-credentials
    googlecredentials: googlecloud/service-key.json
